TDAT: public void test bug2606 ( ) throws exception {  <NL> try {  <NL> this . stmt . execute update ( " drop table if exists test bug2606 " ) ;  <NL> this . stmt <NL>  . execute update ( " create table test bug2606 ( year _ field year ) " ) ;  <NL> this . stmt . execute update ( " insert into test bug2606 values ( 2004 ) " ) ;  <NL>  <NL> prepared statement yr pstmt = this . conn <NL>  . prepare statement ( " select year _ field from test bug2606 " ) ;  <NL>  <NL> this . rs = yr pstmt . execute query ( ) ;  <NL>  <NL> assert true ( this . rs . next ( ) ) ;  <NL>  <NL> assert equals ( 2004 , this . rs . get int ( 1 ) ) ;  <NL>  } finally {  <NL> this . stmt . execute update ( " drop table if exists test bug2606 " ) ;  <NL>  }  <NL>  }  COM: <s> tests the fix for bug 2606 server side prepared statements not returning </s>