TDAT: public void test failure of authorization ( ) {  <NL> mock credit svc . add throw exception ( " authorize " , new runtime exception ( " test robustness of store under test " ) ) ;  <NL>  <NL> string user = " user1 " ;  <NL> double amount = 340 . 99 ;  <NL> try {  <NL> sys under test . purchase ( " item a " , user , amount ) ;  <NL> fail ( " expecting exactly the illegal state exception for some odd reason ( didn ' t want to define my own ) " ) ;  <NL>  } catch ( purchase exception e ) { }  <NL>  }  COM: <s> in this test we test that a failure from credit auth svc </s>