TDAT: public void test unclosed iterator close graph ( ) throws exception {  <NL>  <NL>  / / add in a triple by nodes <NL> graph . add ( ref1 , ref1 , ref1 ) ;  <NL>  <NL> assert false ( graph . is empty ( ) ) ;  <NL> assert equals ( 1 , graph . get number of triples ( ) ) ;  <NL>  <NL>  / / create iterator .  <NL> closable iterator iter = graph . find ( null , null , null ) ;  <NL>  <NL>  / / close the graph .  <NL> graph . close ( ) ;  <NL>  }  COM: <s> test bug where closing the graph without closing the iterator causes a </s>