TDAT: public void test bug16169 ( ) throws exception {  <NL> create table ( " test bug16169 " , " ( field1 smallint ) " ) ;  <NL>  <NL> this . stmt . execute update ( " insert into test bug16169 ( field1 ) values ( 0 ) " ) ;  <NL>  <NL> this . pstmt = this . conn . prepare statement ( " select * from test bug16169 " ) ;  <NL> this . rs = this . pstmt . execute query ( ) ;  <NL> assert true ( this . rs . next ( ) ) ;  <NL>  <NL> assert equals ( 0 , ( ( integer ) rs . get object ( " field1 " ) ) . int value ( ) ) ;  <NL>  }  COM: <s> tests fix for bug 16169 result set </s>