TDAT: public void test navigate next ( ) throws exception {  <NL> begin at sitemap then page ( " home " ) ;  <NL>  <NL> click button with text ( " next " ) ;  <NL> assert no problem ( ) ;  <NL>  <NL> assert content2 ( ) ;  <NL>  <NL>  / / and again <NL> click button with text ( " next " ) ;  <NL> assert no problem ( ) ;  <NL>  <NL> assert content3 ( ) ;  <NL>  <NL>  / / but if we click it again , we get an error <NL> try {  <NL> click button with text ( " next " ) ;  <NL> fail ( " should have thrown an exception " ) ;  <NL>  } catch ( php runtime exception exception e ) {  <NL>  / / expected <NL> assert contains ( " no results found for query " , e . get message ( ) ) ;  <NL>  }  <NL> assert problem ( ) ;  <NL>  <NL>  }  COM: <s> click next to get to the next element </s>