TDAT: public void test get cause ( ) {  <NL>  <NL> exception a cause = new io exception ( " the cause " ) ;  <NL>  <NL> try {  <NL> throw new http exception ( " http exception " , a cause ) ;  <NL>  }  <NL> catch ( http exception e ) {  <NL> assert equals ( " retrieve cause from caught exception " , e . get cause ( ) , a cause ) ;  <NL>  }  <NL>  }  COM: <s> make sure that you can retrieve the cause from an http exception </s>