TDAT: public void validate ( object value ) throws property exception {  <NL> iterator i = verifiers . iterator ( ) ;  <NL>  <NL> while ( i . has next ( ) ) {  <NL> property verifier pv = ( property verifier ) i . next ( ) ;  <NL>  <NL>  / / hmm , do we need a try / catch ?  <NL> try {  <NL> pv . verify ( value ) ;  <NL>  } catch ( verify exception ex ) {  <NL> throw new illegal property exception ( ex . get message ( ) ) ;  <NL>  }  <NL>  }  <NL>  }  COM: <s> validate a given value against all verifiers </s>