TDAT: public void test bug10630 ( ) throws exception {  <NL> connection conn2 = null ;  <NL> statement stmt2 = null ;  <NL>  <NL> try {  <NL> conn2 = get connection with props ( null ) ;  <NL> stmt2 = conn2 . create statement ( ) ;  <NL>  <NL> conn2 . close ( ) ;  <NL> stmt2 . get warnings ( ) ;  <NL> fail ( " should ' ve caught an exception here " ) ;  <NL>  } catch ( sql exception sql ex ) {  <NL> assert equals ( " 08003 " , sql ex . get sql state ( ) ) ;  <NL>  } finally {  <NL> if ( stmt2 ! = null ) {  <NL> stmt2 . close ( ) ;  <NL>  }  <NL>  <NL> if ( conn2 ! = null ) {  <NL> conn2 . close ( ) ;  <NL>  }  <NL>  }  <NL>  }  COM: <s> tests fix for bug 10630 statement </s>